{
    'name': "Plano de Corte Polispan",
    'version': '16.0.1.0.3',
    'description': """Plano de Corte Polispan""",
    'author': "Rodrigo Abrão Madureira.",
    'depends': [
        'sale',
        'sale_management',
        'mrp',
        'mrp_sale_info',
        'stock',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/mrp_cut_plan_views.xml',
        'views/mrp_bom_views.xml',
        'views/product_template_views.xml',
        'views/sale_order_views.xml',
        'views/stock_picking.xml',
        'wizards/sale_order_line_config_views.xml',
        'wizards/transfer_wizard_view.xml',
        'views/template_price_config_view.xml',
        'report/external_layout_boxed.xml',
        'report/mrp_production_template.xml',
        'report/sale.xml',
        'report/purchase.xml',
        'views/mrp_production.xml',
        'views/purchase.xml',
        'report/mrp_cut_plan_mrp_cut_plan_report_pdf.xml',
        'report/purchase.xml'
    ],
    'license': 'LGPL-3',
    'installable': True,
   
}
